name: login_msg_otp_app
description: "Login flutter otp with sms phone"
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^13.2.4
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  formz: ^0.7.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/